### ISSUE TITLE
TRANSFORMER.py

### ISSUE THREAD

**Issue by Mohammadhakimkhah** [Honee-W/CPTNN#2]
Hi , Thank you for your reply 
in TRANSFORMER.py   line94   " local_feat = th.reshape(x.permute(0, 2, 1, 3), (-1, L, C)) "  
 In (0, 2, 1, 3), you should not put (0, 2, 3, 1) instead of (0, 2, 1, 3) ?

**Comment by Honee-W** [comment]
Thanks for your question, i do find this bug however i forget to update the code. Now it has been fixed.
