### ISSUE TITLE
Masking module

### ISSUE THREAD

**Issue by Mohammadhakimkhah** [Honee-W/CPTNN#4]
![Capture](https://github.com/Honee-W/CPTNN/assets/110603758/cc42c5fc-3ac4-4427-9c1e-e6df6082a58e)

In Masking module, the output of 'Gated convolution'  should be given directly to the next convolution layer(According to the picture I sent), but you multiplied it in the previous output, shouldn't the overall output of Masking module be multiplied in the output of the encoder?

**Comment by Honee-W** [comment]
Thanks for the feedback. It's been fixed now.
