### ISSUE TITLE
Downsampler

### ISSUE THREAD

**Issue by Mohammadhakimkhah** [Honee-W/CPTNN#5]
![Capture](https://github.com/Honee-W/CPTNN/assets/110603758/af2fd92b-55d1-401e-aca9-9c36ad2febae)
![Capture1](https://github.com/Honee-W/CPTNN/assets/110603758/880329ef-d880-45d5-8279-0ff2e87cc947)

in Downsampler module, shouldn't you put "Layer-norm" and "PRelu" after 2-D conv ?

**Comment by Mohammadhakimkhah** [comment]
![image](https://github.com/Honee-W/CPTNN/assets/110603758/83b110c9-88f5-4360-afa0-9140e2abbcaf)
![image](https://github.com/Honee-W/CPTNN/assets/110603758/5823846d-6b96-4e60-b38a-b1157556f9e4)

in Upsampler module too, shouldn't put "Layer-norm" and "PRelu" after subpixel convolution ?

**Comment by Honee-W** [comment]
Thanks for the feedback. The code has been updated.
